[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Shuanglin <augusto.yjh@antgroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rand = "0.5.0"