[package]
name = "generic"
version = "0.1.0"
authors = ["Augusto Yao <727004611@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
